### ISSUE TITLE
Installation.yaml is throwing errors

### ISSUE THREAD

**Issue by wwatson13** [gardener/landscaper#102]
**How to categorize this issue?**
Priority: Normal

**What happened**:
Following the tutorials I have deployed and pushed the chart, blueprint and component to a local harbor (btw the documentation on this process in the tutorial is incomplete and in some cases wrong).  Created the target successfully but when creating/applying the installation.yaml I get the following errors.

error: error validating "tutorial/installation.yaml": error validating data: [ValidationError(Installation.spec.blueprint.ref): missing required field "componentName" in cloud.gardener.landscaper.v1alpha1.Installation.spec.blueprint.ref, ValidationError(Installation.spec.blueprint.ref): missing required field "version" in cloud.gardener.landscaper.v1alpha1.Installation.spec.blueprint.ref, ValidationError(Installation.spec): unknown field "componentDescriptor" in cloud.gardener.landscaper.v1alpha1.Installation.spec]; if you choose to ignore these errors, turn validation off with --validate=false

**What you expected to happen**:
A successful installation of ingress-nginx

**How to reproduce it (as minimally and precisely as possible)**:
Use the installation.yaml definition from simple blueprint tutorial

**Anything else we need to know?**:

**Environment**:

- Landscaper version:
- Kubernetes version (use `kubectl version`):
- Others:

**Comment by MrBatschner** [comment]
We recently changed the API structure of the `Installation` resource in PR #93, and the `installation.yaml` from the blueprint tutorial already reflects that change.

Before, the component descriptor was part of the blueprint ref:
```yaml
spec:
  blueprint:
    ref:
      repositoryContext:
        type: ociRegistry
        baseUrl: eu.gcr.io/my-project/comp
      componentName: github.com/gardener/landscaper/ingress-nginx
      version: v0.1.0
      resourceName: ingress-nginx-blueprint
```

Now, the component descriptor is part of the installation spec and the blueprint ref only refers to the component name:
```yaml
spec:
  componentDescriptor:
    ref:
      repositoryContext:
        type: ociRegistry
        baseUrl: eu.gcr.io/gardener-project/landscaper/tutorials/components
      componentName: github.com/gardener/landscaper/ingress-nginx
      version: v0.2.1

  blueprint:
    ref:
      resourceName: ingress-nginx-blueprint
```

Your error message implies that your cluster still has the old custom-resource-definitions from before the change. Did you install Landscaper from the Helm chart and did you pull the latest changes between landscaper installation and running through the tutorial?
