### ISSUE TITLE
Integrate secret stores into landscaper

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#105]
**How to categorize this issue?**

/area security
/kind epic
/priority normal

Currently data can be provided via targets, data objects, configmaps or secrets.
As imports may contain secrets, the support for secret systems like vault is essential.

The goal is _NOT_ that the secrets are never stored in the cluster.
Its currently rather that the import given by the operator/user can come from a secret store.

Targets are also for now out fo scope as they are directly read by the deployers which would mean that they also need support for those engines.
(maybe we could think that targets are during the copying in the context are resolved by the landscaper)

#### Integration Proposal

With that the proposed integration point are the dataobjects.
DataObjects can be provided by users directly as input for installations and they are only used by the landscaper for the templating.
This means that the support for the secret only need to happen in the landscaper

new dataobject structure:

```yaml
apiVersion: landscaper.gardener.cloud/v1alpha1
kind: DataObjects
# either data or fromSecretEngine must be provided
data: <raw data value>
fromSecretStore: # need to find a better name
  type: <secret store type> # e.g. Vault
  config: {} # provider specific config
```

With that structure we would add an additional field that is extensible.
The landscaper would fetch the secret from the engine during the installation reconciliation.
:warning: During the copy into the sub contexts the original secret engine should be preserved and not only the data should be copied.

The first engines should be Vault as the mostly known and used secret store in the opensource.
Currently this engines can be implemented inline but for the future we should think about a generic approach.

The vault data object could look as follow:

```yaml
apiVersion: landscaper.gardener.cloud/v1alpha1
kind: DataObjects
fromSecretStore:
  type: Vault 
  config: # provider specific config
    namespace: secrets/kv/mystore
    field: my kv key # check if we can only support key-value engines or more
    connectionInformation: # optional. should be also configurable in the landscaper
      secretRef:
        name: my-connection
---
apiVersion: v1
kind: Secret
data:
  VAULT_ADDRESS: abc
  VAULT_TOKEN: some token
```
