### ISSUE TITLE
Manifest Deployer

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#11]
In addition to the helm deployer, there should be a simple manifest deployer.
That manifest deployer should just deploy (`kubectl apply`) given manifests to the target cluster.

The same behavior could be archived by using the helm deployer and create a simple helm chart, but most of the times a helm template is to much overhead so a manifest makes sense to ease the use of simple deployments.

The pprovider configuration should look as follows:
```yaml
kind: DeployItem
spec:
  target: 
    name: my-target
    namespace: default
  type: Manifest
  config:
    apiVersion: manifest.landscaper.gardener.cloud
    kind: ProviderConfiguration

    manifests: # list of k8s manifests to deploy
    - apiVersion: v1
       kind: Secret
       data:
          config: here goes my data
```
