### ISSUE TITLE
Landscaper `Target` CRs should support an indirection through secretRef

### ISSUE THREAD

**Issue by loewenstein** [gardener/landscaper#118]
**How to categorize this issue?**
/area security
/kind enhancement
/priority normal

**What would you like to be added**:
I would like to be able to create Kubernetes `Target`s like:
```yaml
apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Target
metadata:
  name: my-target-cluster
spec:
  type: landscaper.gardener.cloud/kubernetes-cluster
  config:
    kubeconfig: 
        secretRef: <the secret containing the kubeconfig>
```

Not sure where exactly to put the secretRef, maybe that depends also on what else could be part of a target's config.

**Why is this needed**:
This wouldn't add much to security per se, if etcd as a whole is configured to store data encrypted. However, if there will be a Landscaper hosted in or listening to the Garden cluster, there are already `Secret`s for every `Shoot` and there would be no need to create and rotate separate ServiceAccounts or keep copying the the kubeconfig in those `Secret`s when they are rotated.
