### ISSUE TITLE
Wrong Documentation for GoTemplating function "include"

### ISSUE THREAD

**Issue by Empiire00** [gardener/landscaper#1279]
**How to categorize this issue?**

/area documentation
/kind bug
/priority 4

**What happened**:
I tried using the blueprint templating and looked up the documentation section about available templating functions in helm ( see https://github.com/gardener/landscaper/blob/a98feab37e6ed4a2154d88b689a4e2e108e952c2/docs/usage/Templating.md#L124-L125 ).

**What you expected to happen**:
I expected the file to behave like helm's "include" function.
However, it's behavior is more similar to the "template" function. 

**How to reproduce it (as minimally and precisely as possible)**:
I used the following minimal working example in my blueprint:
deploy-executions.yaml.tmpl:
```yaml
{{- define "someFunction" }}
some content
{{- end }}

deployExecutions:
- name: someName
  someKey: {{ include "someFunction" $ }}
```

blueprint.yaml:
```yaml
deployExecutions:
  - name: deploy-execution
    type: GoTemplate
    file: /deploy-execution.yaml.tmpl
```

**Anything else we need to know?**:
See this so question for an explanation about the difference of "template" and "include": https://stackoverflow.com/q/71086697
See this part of the code, which implements the "include" function:
https://github.com/gardener/landscaper/blob/a98feab37e6ed4a2154d88b689a4e2e108e952c2/pkg/landscaper/installations/executions/template/gotemplate/gotemplate.go#L76-L92

**Environment**:

- Landscaper version:
- Kubernetes version (use `kubectl version`):
- Others:
