### ISSUE TITLE
Conditional SubInstallations

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#142]
**How to categorize this issue?**

/area usability
/kind epic
/priority 3

**What would you like to be added**:

Currently subinstallation defined in blueprints are a hardcoded list of included installations.
For some scenarios it is needed that the different subinstallations are needed based on the imports of a blueprint.

Possible Implementation:
1. Have a dedicated condition field on the subinstallation template:
  - the idea is to have a field in the subinstallation template that is prevalidated with thegiven imports. Then condition must return `true` or `false` and decide whether the subinstallation should be deployed or not.
  ```
  subinstallations:
  - apiVersion: ...
     kind: InstallationTemplate
     condition: "if imports.a" # own simple condition syntax
     condition: (( if imports.a  )) # use spiff
  ```
  - Pro: simple to implement and simple to use. Still have easy validation
     Con: does not cover all scenarios. we need a syntax or templating mechanism
2. have subinstallation executors.
    - similar to the deploy item executors also have subinstallation executors.
    ```
    subinstallationExecutor: # can be also combined with the deployexecution via another key
    - name: my-subs
      type: GoTemplate
      template: |
        subinstallations:
        {{ if imports.a }}
        - apiVersion: ...
           kind: InstallationTemplate
        {{ end }}
    ```
    - Pro: same functionaility as for the deploy items: loops, conditions more complex conditions.
      Con: validation always needs imports (temapltes always need to be rendered).

*Scenarios*:
- install a database with a backup bucket. That backup bucket needs to support different cloudproviders. so we could imageine to have differnt blueprints for differnet cloudproviders and based on a import type we only use the corresponding blueprint.
