### ISSUE TITLE
Manifest Deployer uses internal version for Status

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#152]
**How to categorize this issue?**

/area operations
/kind bug
/priority 3

**What happened**:
A deploy item of type `landscaper.gardener.cloud/kubernetes-manifest` got the following status:
```yaml
status:
  observedGeneration: 1
  phase: Succeeded
  providerStatus:
    apiVersion: manifest.deployer.landscaper.gardener.cloud/__internal
    kind: ProviderStatus
    managedResources:
    - policy: manage
      resource:
        apiVersion: v1
        kind: Namespace
        name: fooo
        namespace: ""
```

**What you expected to happen**:
`status.providerStatus.apiVersion` should be versioned, not `__internal`

**Environment**:

- Landscaper version: latest master commit is `9b9406e36d3824b800ecef22bcbd13eb116529ba`
