### ISSUE TITLE
Templating of deployment-webhooks.yaml fails during helm deployment of Landscaper

### ISSUE THREAD

**Issue by robertgraeff** [gardener/landscaper#178]
**How to categorize this issue?**
/area control-plane
/kind bug
/priority 3

**What happened**:
The helm deployment of the landscaper fails when I use the component descriptor from [here](eu.gcr.io/sap-se-gcr-k8s-private/cnudie/gardener/development/component-descriptors/github.com/gardener/landscaper@sha256:6da2067a520386a6b375a5c701a4acb86c48e1367ce09304497f834a5930c3c0) and these values.yaml:

```yaml
"controller":
  "image":
    "repository": "eu.gcr.io/gardener-project/landscaper/landscaper-controller"
    "tag": "v0.8.0-dev-0ea948959c4f795d191fa42fcd7257852b71fa9d"
"landscaper":
  "repositoryContext":
    "baseUrl": "eu.gcr.io/sap-se-gcr-k8s-private/cnudie/gardener/development"
    "type": "ociRegistry"
"webhooksServer":
  "image":
    "repository": "eu.gcr.io/gardener-project/landscaper/landscaper-webhooks-server"
    "tag": "v0.8.0-dev-0ea948959c4f795d191fa42fcd7257852b71fa9d"
```

The error message is:
template: landscaper/templates/deployment-webhooks.yaml:39:117: executing "landscaper/templates/deployment-webhooks.yaml" at <.Values.image.tag>: nil pointer evaluating interface {}.tag

I guess that the [deployment-webhooks.yaml template](https://github.com/gardener/landscaper/blob/0ea948959c4f795d191fa42fcd7257852b71fa9d/charts/landscaper/templates/deployment-webhooks.yaml#L39) evaluates the default expression `.Values.image.tag` in line 39 even if it not needed. The values.yaml does not contain a top-level `image` section, because the repositories and tags are specified in the `webhooksServer` and `controller` section. 

**Environment**:

- Landscaper version: commit 0ea948959c4f795d191fa42fcd7257852b71fa9d - after [pull request 172](https://github.com/gardener/landscaper/pull/172)
