### ISSUE TITLE
Installation without Executions/Subinstallations doesn't get a phase

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#189]
**How to categorize this issue?**

/area operations
/kind bug
/priority 3

**What happened**:
I created the installation resource below, which has neither subinstallations nor executions.
The landscaper reconciled the resource without showing errors, but the installation did not get any phase and thus looks like the landscaper did not reconcile it properly.

```yaml
apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: mock-installation
spec:

  componentDescriptor:
    inline:
      meta:
        schemaVersion: v2

      component:
        name: mock-installation
        version: 1.0.0

        provider: internal

        repositoryContexts:
          - type: ociRegistry
            baseUrl: "example.com/test"

        sources: []
        componentReferences: []

        resources: []

  blueprint:
    inline:
      filesystem:
        blueprint.yaml: |
          apiVersion: landscaper.gardener.cloud/v1alpha1
          kind: Blueprint
```

**What you expected to happen**:
This is basically a no-op installation, so if the imports are fulfilled, it should be `Succeeded` by definition.

**How to reproduce it (as minimally and precisely as possible)**:
Apply the above manifest into a landscaper cluster.

**Environment**:

- Landscaper version: `v0.9.0-dev`
