### ISSUE TITLE
GitHub access method for blueprints and component descriptors

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#20]
Currently it is only possible to use blueprints defined inline or in an oci registry.
Also a component descriptor can only be referenced using a ociregistry.

OCI Artifacts should be definitely used for production deployments, but for simple application or tests it should be possible to read blueprints and component descriptors from a github repository.

__Blueprints__:

to access blueprints from github the proposed implementation would be another component descriptor access type.
```yaml
resources:
- type: blueprint
  access:
    type: github
    repository: github.com/my-org/my-repo
    revision: sha or tag or branch
    path: /path/to/blueprint
```
