### ISSUE TITLE
Add component descriptor as blueprint import

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#222]
**How to categorize this issue?**

/area delivery
/kind enhancement
/priority 2

**What would you like to be added**:

Currently it is possible to import dataobjects or targets (targetlists).
But as some component require additional information from component descriptor that are not part of their own component descriptor it is necessary to have them as import.

So it should be possible for blueprints to define imports of type ComponentDescriptor or a list of component descriptors.
In the installation these imports can then be satisfied by either providing the import directly or referecing it using a componentName and version
```
imports:
  componentDescriptors:
  - name: my-import
    configMap: ...
  - name: my-other-cd
    componentName: abc
    version: 123
```
