### ISSUE TITLE
Spiff templating error

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscaper#228]
**How to categorize this issue?**

/area robustness
/kind bug
/priority 3

**What happened**:
The installation given below works fine. If the `exportExecutions` of the blueprint belonging to the top-level installation are replaced with an equivalent spiff template, it fails:
```yaml
          exportExecutions:
          - type: Spiff
            template:
              exports:
                dataExp: (( values.dataobjects.dataExp ))
```
```
  Last Error:
    Last Transition Time:  2021-06-15T15:07:47Z
    Last Update Time:      2021-06-15T15:07:49Z
    Message:               unable to init spiff templater: unknown type (struct {}) during sanitization: struct {}{}

    Operation:          Completing
    Reason:             ConstructExports
```

**What you expected to happen**:
The spiff templating expression should produce the same result as the gotemplate one.

**How to reproduce it (as minimally and precisely as possible)**:
Apply this manifest (secret/target required) once as given here and once with spiff templating for the export execution:
```yaml
apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: mockinst
  namespace: test
spec:

  componentDescriptor:
    inline:
      meta:
        schemaVersion: v2

      component:
        name: mock-installation
        version: 1.0.0

        provider: internal

        repositoryContexts:
          - type: ociRegistry
            baseUrl: "example.com/test"

        sources: []
        componentReferences: []

        resources: []

  imports:
    data:
    - name: dataImp
      secretRef:
        key: value
        name: "my-secret"
    targets:
    - name: targetImp
      target: "#my-target"
  
  exports:
    data:
    - name: dataExp
      dataRef: dataExp
    # targets:
    # - name: targetExp
    #   target: targetExp

  blueprint:
    inline:
      filesystem:
        blueprint.yaml: |
          apiVersion: landscaper.gardener.cloud/v1alpha1
          kind: Blueprint

          annotations:
            local/name: root
            local/version: 1.0.0

          imports:
          - name: dataImp
            type: data
            schema:
              type: string
          - name: targetImp
            type: target
            targetType: landscaper.gardener.cloud/mock

          exports:
          - name: dataExp
            type: data
            schema:
              type: string
          
          exportExecutions:
          - type: GoTemplate
            template: |
              exports:
                dataExp: {{ .values.dataobjects.dataExp }}

          subinstallations:
          - apiVersion: landscaper.gardener.cloud/v1alpha1
            kind: InstallationTemplate
            name: subinst
            imports:
              data:
              - name: data
                dataRef: dataImp
              targets:
              - name: target
                target: targetImp
            importDataMappings:
              dataImp: (( data ))
              targetImp: (( target ))
            exports:
              data:
              - name: dataExp
                dataRef: dataExp
              targets:
              - name: targetExp
                target: targetExp
            blueprint:
              filesystem:
                blueprint.yaml: |
                  apiVersion: landscaper.gardener.cloud/v1alpha1
                  kind: Blueprint
                  deployExecutions:
                  - type: GoTemplate
                    template: |
                      deployItems:
                      - name: submain-import
                        type: landscaper.gardener.cloud/mock
                        config:
                          apiVersion: mock.deployer.landscaper.gardener.cloud/v1alpha1
                          kind: ProviderConfiguration
                          providerStatus:
                            apiVersion: mock.deployer.landscaper.gardener.cloud/v1alpha1
                            kind: ProviderStatus
                  imports:
                  - name: dataImp
                    type: data
                    schema:
                      type: string
                  - name: targetImp
                    type: target
                    targetType: landscaper.gardener.cloud/mock
                  exports:
                  - name: dataExp
                    type: data
                    schema:
                      type: string
                  - name: targetExp
                    type: target
                    targetType: landscaper.gardener.cloud/mock
                  exportExecutions:
                  - type: Spiff
                    template:
                      exports:
                        dataExp: (( values.dataobjects.dataImp ))
                        targetExp: (( values.targets.targetImp.spec ))
```

**Environment**:

- Landscaper version: a `v0.9.0-dev` version, didn't try it with current master yet
