### ISSUE TITLE
Installation is never deleted

### ISSUE THREAD

**Issue by robertgraeff** [gardener/landscaper#230]
**How to categorize this issue?**

/area robustness
/kind bug
/priority 3

**What happened**:
Suppose an installation fails, because its blueprint cannot be resolved:

```yaml
  lastError:
    ...
    message: 'unable to find blueprint blueprint in component descriptor: NotFound'
    operation: InitPrerequisites
    reason: ResolveBlueprint
  observedGeneration: 0
  phase: Failed
```

I run `kubectl delete installation ...` for the installation. The installation gets a deletion timestamp, but the landscaper does not delete it. After an hour it is still there.

**What you expected to happen**:
The installation should be deleted.

I am aware that checks are done before a deletion, and that they might need the blueprint. But in this case the failure of the installation occurred so early that no execution and deploy item was created. Shouldn't it be possible to delete the installation? 

**Environment**:
The current version of the landscaper in the master branch.
