### ISSUE TITLE
Installation imports without explicit key

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/landscaper#235]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 5

**What would you like to be added**:

Allow Installation data importing from `secretRef`  and `configMap`without explicitly defining a `key`.
```
  imports:
    data:
      - name: seedBackupCredentials
        secretRef:
          name: ${backup_secret_name}
          namespace: ${installation_namespace}
          key: seedBackupCredentials # not required any more
```

Currently required:
```
apiVersion: v1
data:
  seedBackupCredentials: <base64 of accessKeyID + secretAccessKey>
kind: Secret
```

Not. requiring a specific key takes every key available in the secret/config map

```
apiVersion: v1
data:
    accessKeyID: <id>
    secretAccessKey: <more secret stuff>
kind: Secret
```

**Why is this needed**:
Especially for secrets, it is uncommon to define an artificial top-level key to satisfy the. landscaper imports.
