### ISSUE TITLE
Ability to specify file for layer of type application/vnd.gardener.landscaper.blueprint.v1 (not the whole directory)

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/landscaper#236]
**How to categorize this issue?**

/kind enhancement
/priority 5

**What would you like to be added**:

The ability for CTF layers of media type `application/vnd.gardener.landscaper.blueprint.v1` to only contain the `blueprint.yaml ` without having to isolate the `blueprint.yaml` in a dedicated directory.

**Why is this needed**:

Currently, to add a layer to the CTF with media type `application/vnd.gardener.landscaper.blueprint.v1`, the whole directory has to be imported with the following configuration:

```
type: landscaper.gardener.cloud/blueprint
name: gardenlet-blueprint
relation: local
input:
  type: "dir"
  path: "./pkg/gardenlet"
  compress: true
  mediaType: "application/vnd.gardener.landscaper.blueprint.v1+tar+gzip"
```

This is a problem because Gardener has the bleuprint.yaml at the root directory in the code path.
It should be possible to only define this file to be included and not the whole directory.

**Background**: As far as I understood from @schrodit, this is because a blueprint layer has to be always a `tar` archive.
If the blueprint was imported as a file only,  the layer would be in  `gzip` format.
However, I am not sure what the file format has to do with the ability to specify the blueprint.yaml as a single file.
If it always needs to be a `tar` archive, then the `component-cli` could always encode referenced file of media type `application/vnd.gardener.landscaper.blueprint.v1` as `tar` archives and not `gzip`.

```
type: landscaper.gardener.cloud/blueprint
name: gardenlet-blueprint
relation: local
input:
  type: "file"
  path: "./pkg/gardenlet/blueprint.yaml"
  compress: true
  mediaType: "application/vnd.gardener.landscaper.blueprint.v1+gzip"
```
