### ISSUE TITLE
Container Deploy Item: Permission denied when writing to shared-volume (`STATE_PATH`, `EXPORTS_PATH`)

### ISSUE THREAD

**Issue by Haegi** [gardener/landscaper#264]
**How to categorize this issue?**

/area container-deployer
/kind bug
/priority 2

**What happened**:

When trying to write a (custom) Container Deploy Item according to [this guide](https://github.com/gardener/landscapercli/blob/master/docs/commands/container_deployer/add_container_di.md), the writing of data to the `STATE_PATH` & `EXPORTS_PATH` (shared-volume) doesn't work because of some `Permissions denied` problem.

For example `echo "test" > $STATE_PATH/test.txt` will result in `/data/ls/shared/state/test.txt: Permission denied`.

For my thoughts on what the root cause could be, please take a look at the "Anything else we need to know?" section.

**What you expected to happen**:

It should be possible to write to the shared-volume (`STATE_PATH` & `EXPORTS_PATH`) within a custom Container Deploy Item.

**How to reproduce it (as minimally and precisely as possible)**:

Try to run the script from [this guide](https://github.com/gardener/landscapercli/blob/master/docs/commands/container_deployer/add_container_di.md#the-example-script-program), which writes something to the shared-volume.

Or reproduce it by running this pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: init-permissions
spec:
  automountServiceAccountToken: false
  containers:
  - image: europe-west3-docker.pkg.dev/sap-se-gcp-istio-dev/public/create-file:latest
    name: main
    command:
    - ./script.sh
    env:
    - name: DIR_PATH
      value: /data/ls/shared
    volumeMounts:
    - mountPath: /data/ls/shared
      name: shared-volume
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
  initContainers:
  - image: europe-west3-docker.pkg.dev/sap-se-gcp-istio-dev/public/mkdir:latest
    name: init
    command:
    - ./script.sh
    env:
    - name: DIR_PATH
      value: /data/ls/shared
    volumeMounts:
    - mountPath: /data/ls/shared
      name: shared-volume
  volumes:
  - emptyDir: {}
    name: shared-volume
```

The `mkdir` container just runs:
```bash
#!/bin/sh
set -euo pipefail
echo "create directory 'test' in shared volume"
mkdir $DIR_PATH/test
```

And the `create-file` container runs:
```bash
#!/bin/sh
set -euo pipefail
echo "create file in directory"
echo "test" > $DIR_PATH/test/values.txt
```

**Anything else we need to know?**:

I think the problem (as reproduced in the "How reproduce it" section) is that the init container runs with `root` and creates the `/data/ls/shared/state/` and the `/data/ls/shared/exports/values` directory/file with the `root` user. But the container provided by the developer runs with user `1001`, which is totally okay because this arbitrary code shouldn't run as `root`. But the user `1001` can't access the directories created by the init container (`root` user). To fix this problem, the init container could also run as user `1001`.

**Environment**:

- Landscaper version: `v0.10.0`
- Kubernetes version (use `kubectl version`): Server: `v1.19.12` (Gardener Cluster)
- Others: For the simple permissions test I've used k8s version `v1.21.1` (Gardener Cluster) to exclude problems of older k8s versions.
