### ISSUE TITLE
Add context awareness for landscaper protocol schemes in JSON schema references

### ISSUE THREAD

**Issue by reshnm** [gardener/landscaper#303]
/area usability
/kind enhancement
/priority 5

**What would you like to be added**:

Imagine the following scenario:

**Component A**

blueprint
```
imports:
  name: foo
  type: data
  schema:
    $ref: "cd://resources/foo-definition"
```

JSON schema _foo-definition_
```
"properties": {
  "bar": {
    "$ref": "cd://resources/bar-definition"
  }
}
```

**Component B**

blueprint
```
imports:
  name: foo
  type: data
  schema:
    $ref: "cd://rcomponentReferences/component-a/resources/foo-definition"
```

This scenario would fail when instantiating blueprint of _component B_.
The reason is, that during the evaluation of the JSON schema of type _foo_, the context for reference `cd://resources/bar-definition` is no longer _component A_, but _component B_.
However, _component B_ has no own resource by the name _bar-definition_.

**Why is this needed**:

The usage JSON schemas of referenced components is a valid use case.
This means that Landscaper reference types should be supported.
