### ISSUE TITLE
Unable to fetch component descriptor from plain HTTP repository

### ISSUE THREAD

**Issue by reshnm** [gardener/landscaper#329]
**How to categorize this issue?**

/area operations
/kind bug
/priority 3

**What happened**:

Deploy the landscaper with a configuration as following (assuming namespace "ls-system", oci registry service name "oci-registry"):

```yaml
landscaper:
  registryConfig:
    allowPlainHttpRegistries: true
    secrets:
      default: {
        "auths": {
          "http://oci-registry.ls-system:5000": {
            "auth": "cmVndXNlcjokMnkkMTAkZklHcG1VYVdyMktGcGpJUWgyN3FhLlBLWUJUTlNhY1c5Qk5aZkx5T1Q1VmZZcFM0WmVzNE8KCg=="
          }
        }
      }

  deployers:
  - container
  - helm
  - manifest
```

Create an installation that references a component descriptor stored in the plain http repository "oci-registry.ls-system:5000".

```yaml
apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: my-ingress
spec:
  componentDescriptor:
    ref:
      repositoryContext:
        type: ociRegistry
        baseUrl: oci-registry.ls-system:5000
      componentName: github.com/reshnm/landscaper/nginx-ingress
      version: v0.1.0

  blueprint:
    ref:
      resourceName: ingress-nginx-blueprint
```

The installation will fail will the following error:

```
unable to resolve component descriptor for ref &v1alpha1.ComponentDescriptorReference{RepositoryContext:(*v2.UnstructuredTypedObject)(0xc0009cdf50), ComponentName:"github.com/reshnm/landscaper/nginx-ingress", Version:"v0.1.0"}: unable to fetch manifest from ref oci-registry.ls-system:5000/component-descriptors/github.com/reshnm/landscaper/nginx-ingress:v0.1.0: unable to create transport: unable to create transport: Get "https://oci-registry.ls-system:5000/v2/": http: server gave HTTP response to HTTPS client
```

**What you expected to happen**:

When `allowPlainHttpRegistries` is set to `true`, the landscaper should be able to pull resources using http transport.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Landscaper version: 0.13.0
- Kubernetes version (use `kubectl version`): N/A
- Others:
