### ISSUE TITLE
Schema reference within localTypes fails

### ISSUE THREAD

**Issue by achimweigel** [gardener/landscaper#348]
**How to categorize this issue?**

/area usability
/kind bug
/priority 3

**What happened**:

Assume you have a blueprint with local schema references in the `localTypes` section as here:

```yaml
localTypes:
  resourceRequirements:
    properties:
      limits:
        "$ref": "local://resourceList"
      requests:
        "$ref": "local://resourceList"
  resourceList:
    properties:
      cpu:
        type: string
      memory:
        type: string
```

If an installation is deployed referencing this blueprint, this error is reported:

`Get "local://resourceList": unsupported protocol scheme "local": `

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Landscaper version: 
- Kubernetes version (use `kubectl version`): 
- Others:
