### ISSUE TITLE
Export targets are not created

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/landscaper#396]
**How to categorize this issue?**

/kind bug
/priority 2

**What happened**:

Export targets are not created for my example installation. The data export's `data objects` are created fine.

This is the installation

```
apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: virtual-garden
spec:
  componentDescriptor:
    ref:
      repositoryContext:
        type: ociRegistry
        baseUrl: eu.gcr.io/gardener-project/development
      componentName: github.com/gardener/virtual-garden
      version: v0.1.0-dev-e976b1ba58649899d99f8073685c5a457287dbf1

  blueprint:
    ref:
      resourceName: blueprint

  imports:
    targets:
    - name: runtimeCluster
      target: "#runtime-cluster"

  # static data to not require to import config map
  importDataMappings:
    runtimeClusterSettings:
      namespace: garden
      infrastructureProvider: aws

    virtualGarden:
      deleteNamespace: true
      etcd:
        storageClassName: my-virtual-garden-storage-class
        handleETCDPersistentVolumes: true
      kubeAPIServer:
        replicas: 1
        dnsAccessDomain: ""
        gardenerControlplane:
          validatingWebhookEnabled: true
          mutatingWebhookEnabled: true

  exports:
    data:
    - name: virtualGardenApiserverCaPem
      dataRef: "virtual-garden-apiserver-ca-pem"
    - name: etcdCaPem
      dataRef: "etcd-ca-pem"
    - name: etcdClientTlsPem
      dataRef: "etcd-client-tls-pem"
    - name: etcdClientTlsKeyPem
      dataRef: "etcd-client-tls-key-pem"
    - name: virtualGardenEndpoint
      dataRef: "virtual-garden-endpoint"
    - name: etcdUrl
      dataRef: "etcd-url"

  # target not created
    targets:
    - name: virtualGardenCluster
      target: "virtual-garden-cluster"

```

**What you expected to happen**:

The target to be created according to the documentation [here](https://github.com/gardener/landscaper/blob/master/docs/usage/Installations.md#target-exports).

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Landscaper version: v0.19
- Kubernetes version (use `kubectl version`):
- Others:
