### ISSUE TITLE
Problem with marshalling complete secrets

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/landscaper#398]
**How to categorize this issue?**

/kind bug
/priority 3

**What happened**:

Installation import is specified to import all keys from the secret 

```
      - name: landscaperControlplaneInternalDomain
        secretRef:
          name: landscaper-controlplane-internal-domain
```

The secret looks like this:

```
apiVersion: v1
kind: Secret
metadata:
  name: landscaper-controlplane-internal-domain
  namespace: ls-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: abc
    AWS_SECRET_ACCESS_KEY: cde
```

the landscaper reports on the installation:

```
Warning  ImportsSatisfied  7m52s (x1072 over 17m)  Landscaper  (Inst gardener-controlplane).internalDomainCredentials: unable to get data object for 'internalDomainCredentials': unable to marshal secret data as map: json: error calling MarshalJSON for type json.RawMessage: invalid character 'A' looking for beginning of value
```

**What you expected to happen**:

The secret keys to be successfully imported.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Landscaper version:
- Kubernetes version (use `kubectl version`):
- Others:
