### ISSUE TITLE
Installation status target import propagation

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#41]
**How to categorize this issue?**

/kind bug
/priority normal

**What happened**:

When a import is defined for an installation it writes the source to the installations status.
The status should distinguish between a data and target import but currently all imported data is written to the status as data import.
```
imports:
  - configGeneration: "0"
    name: config
    type: dataobject
  - configGeneration: "1"
    dataRef: '#runtime-cluster'
    name: runtimeCluster
    type: dataobject
  - configGeneration: "1"
    dataRef: '#garden-cluster'
    name: gardenCluster
    type: dataobject
```

**What you expected to happen**:

The landscaper should write a target state for target imports.

**How to reproduce it (as minimally and precisely as possible)**:

Create an installation that imports a target.
