### ISSUE TITLE
Import all keys from data import

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/landscaper#410]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 2

**What would you like to be added**:

It would be very helpful if the landscaper can import top-level fields from a secret-ref and config-map ref.
It is already possible to import all keys from a secret like so

```
- name: gardenerAdmissionController
  secretRef:
    name: landscaper-controlplane-config

```

This causes all keys in the secret to being mapped to the field `gardenerAdmissionController`  in the blueprint.
However, the problem is, that every top-level field has to specify the key explicitly.

Let's say we have those imported top-level field in the blueprint:
- cert1
- cert2
- other

Then I am forced to declare my imports in the Installation like so:

```
- name: cert1
  secretRef:
    name: landscaper-controlplane-config
    key: cert1
- name: cert2
  secretRef:
    name: landscaper-controlplane-config
    key: cert2
- name: other
  secretRef:
    name: landscaper-controlplane-config
    key: other
```

What is more succinct is the following:
- note that no top-level field name is declared (just means: import all keys from the secret as a top-level field)

```
- secretRef:
    name: landscaper-controlplane-config
``` 

**Why is this needed**:

It would greatly simplify the generation of installations.
- the installation rendering does not have to be adjusted based on the imports (if my import data does not contain the optional `cert2` the installation cannot declare the field `cert2`)
- the Installation is not blown up with 1:1 mappings

Would be nice to get feedback on this as I am planning to start on an installation generator soon.
