### ISSUE TITLE
Inline Component Descriptor

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#72]
**How to categorize this issue?**

/area dev-productivity
/kind enhancement
/priority normal

**What would you like to be added**:

Currently it is possible to specify inline blueprint in an installation so that a remote blueprint nor a remote component descriptor is needed.
If a remote component descriptor is needed with a inline blueprint. It can be specified using `blueprint.inline.cdRef`.

For a local dev workflow it would be also beneficial to not have the requirement for a remote registry at all.
Therefore it should be also possible to specify the component descriptor inline.

To align this change with the current blueprint spec is should be possible to have different different combination of blueprint and component descriptor:
- remote blueprint and remote component descriptor
- inline blueprint and inline component descriptor
- inline blueprint with remote component descriptor
- remote blueprint and inline component descriptor

The proposed new blueprint spec could look like the following.
The attribute names would need to be adjusted. (e.g `.spec.blueprint.blueprint` seems wrong)
```yaml
apiVersion: landscaper.gardener.cloud/v1alpha1 # maybe we need a v1alpha2
kind: Installation
spec:
  blueprint:
    componentDescriptor:
      ref:
        repositoryContext: # optional, defaulted to landscaper repo context
          type: ociRegistry
          baseUrl: "myregistry"
        name: "github.com/gardener/gardener"
        version: ""
      inline:  # here goes the component descriptor
        meta:
          schemaVersion: 2
        component: {} # ...

    blueprint:
      ref:
        resourceName: "my-blueprint" # blueprint resource will be fetched from the component descriptor
      inline:
        blueprint.yaml:
           apiVersion: landscaper.gardener.cloud/v1alpha1
           kind: Blueprint
           # ....
```

Resources that need to be adjusted:
- the go type definition (note to also run `make generate`): https://github.com/gardener/landscaper/blob/master/pkg/apis/core/v1alpha1/types_installation.go#L218
- the component descriptor is resolved in the installation operation: https://github.com/gardener/landscaper/blob/master/pkg/landscaper/installations/operation.go#L70
  - note to also handle the resolved component descriptor (either empty list or we also have to provide the transitive dependencies): https://github.com/gardener/landscaper/blob/master/pkg/landscaper/installations/operation.go#L79 
- the blueprint is directly fetched from the component desscriptor when resolved. So another path is needed when the component descriptor is locally resolved: https://github.com/gardener/landscaper/blob/master/pkg/landscaper/blueprints/resolve.go#L75

Other things to consider:
- should we also allow inline component descriptors in the installation template: https://github.com/gardener/landscaper/blob/master/pkg/apis/core/v1alpha1/types_installationtemplate.go#L52
