### ISSUE TITLE
Deployitem: error":"Object 'Kind' is missing in 'unstructured object has no kind' for echo-server

### ISSUE THREAD

**Issue by enrico-kaack-comp** [gardener/landscaper#90]
**How to categorize this issue?**

/area unknown
/kind bug
/priority normal

**What happened**:
The installation of an installation with an inline blueprint for the echo server fails with the following:

<details>
<summary>log</summary>

```
{"level":"info","ts":"2021-01-14T14:19:51.215Z","logger":"controllers.Installations","msg":"reconcile","resource":"landscaper-local-test/example-echo-server"}
{"level":"debug","ts":"2021-01-14T14:19:51.231Z","logger":"controller-runtime.controller","msg":"Successfully Reconciled","controller":"installation","request":"landscaper-local-test/example-echo-server"}
{"level":"info","ts":"2021-01-14T14:19:51.232Z","logger":"controllers.Installations","msg":"reconcile","resource":"landscaper-local-test/example-echo-server"}
{"level":"info","ts":"2021-01-14T14:19:51.375Z","logger":"controllers.Execution","msg":"reconcile","resource":"landscaper-local-test/example-echo-server"}
{"level":"info","ts":"2021-01-14T14:19:51.375Z","logger":"controllers.Execution","msg":"reconcile annotation found","execution":"landscaper-local-test/example-echo-server","operation":"reconcile"}
{"level":"debug","ts":"2021-01-14T14:19:51.387Z","logger":"controller-runtime.controller","msg":"Successfully Reconciled","controller":"execution","request":"landscaper-local-test/example-echo-server"}
{"level":"info","ts":"2021-01-14T14:19:51.387Z","logger":"controllers.Execution","msg":"reconcile","resource":"landscaper-local-test/example-echo-server"}
{"level":"error","ts":"2021-01-14T14:19:51.393Z","logger":"controller-runtime.controller","msg":"Reconciler error","controller":"execution","request":"landscaper-local-test/example-echo-server","error":"Operation cannot be fulfilled on executions.landscaper.gardener.cloud \"example-echo-server\": the object has been modified; please apply your changes to the latest version and try again"}
{"level":"debug","ts":"2021-01-14T14:19:51.404Z","logger":"controller-runtime.controller","msg":"Successfully Reconciled","controller":"installation","request":"landscaper-local-test/example-echo-server"}
{"level":"info","ts":"2021-01-14T14:19:51.404Z","logger":"controllers.Installations","msg":"reconcile","resource":"landscaper-local-test/example-echo-server"}
{"level":"error","ts":"2021-01-14T14:19:51.413Z","logger":"controllers.Installations","msg":"unable to update installation","error":"Operation cannot be fulfilled on installations.landscaper.gardener.cloud \"example-echo-server\": the object has been modified; please apply your changes to the latest version and try again"}
{"level":"debug","ts":"2021-01-14T14:19:51.413Z","logger":"controller-runtime.controller","msg":"Successfully Reconciled","controller":"installation","request":"landscaper-local-test/example-echo-server"}
{"level":"info","ts":"2021-01-14T14:19:51.413Z","logger":"controllers.Installations","msg":"reconcile","resource":"landscaper-local-test/example-echo-server"}
{"level":"debug","ts":"2021-01-14T14:19:51.424Z","logger":"controller-runtime.controller","msg":"Successfully Reconciled","controller":"installation","request":"landscaper-local-test/example-echo-server"}
{"level":"info","ts":"2021-01-14T14:19:52.393Z","logger":"controllers.Execution","msg":"reconcile","resource":"landscaper-local-test/example-echo-server"}
{"level":"info","ts":"2021-01-14T14:19:52.404Z","logger":"controllers.ContainerDeployer","msg":"reconcile","resource":"landscaper-local-test/example-echo-server-deploy-lls6f"}
{"level":"debug","ts":"2021-01-14T14:19:52.404Z","logger":"controller-runtime.controller","msg":"Successfully Reconciled","controller":"deployitem","request":"landscaper-local-test/example-echo-server-deploy-lls6f"}
{"level":"info","ts":"2021-01-14T14:19:52.404Z","logger":"controllers.HelmDeployer","msg":"reconcile","resource":"landscaper-local-test/example-echo-server-deploy-lls6f"}
{"level":"info","ts":"2021-01-14T14:19:52.414Z","logger":"controllers.ContainerDeployer","msg":"reconcile","resource":"landscaper-local-test/example-echo-server-deploy-lls6f"}
{"level":"debug","ts":"2021-01-14T14:19:52.414Z","logger":"controller-runtime.controller","msg":"Successfully Reconciled","controller":"deployitem","request":"landscaper-local-test/example-echo-server-deploy-lls6f"}
{"level":"info","ts":"2021-01-14T14:19:52.414Z","logger":"controllers.Installations","msg":"reconcile","resource":"landscaper-local-test/example-echo-server"}
{"level":"debug","ts":"2021-01-14T14:19:52.420Z","logger":"controller-runtime.controller","msg":"Successfully Reconciled","controller":"deployitem","request":"landscaper-local-test/example-echo-server-deploy-lls6f"}
{"level":"info","ts":"2021-01-14T14:19:52.420Z","logger":"controllers.HelmDeployer","msg":"reconcile","resource":"landscaper-local-test/example-echo-server-deploy-lls6f"}
{"level":"debug","ts":"2021-01-14T14:19:52.422Z","logger":"controller-runtime.controller","msg":"Successfully Reconciled","controller":"execution","request":"landscaper-local-test/example-echo-server"}
{"level":"info","ts":"2021-01-14T14:19:52.422Z","logger":"controllers.Execution","msg":"reconcile","resource":"landscaper-local-test/example-echo-server"}
{"level":"info","ts":"2021-01-14T14:19:52.422Z","logger":"controllers.ContainerDeployer","msg":"reconcile","resource":"landscaper-local-test/example-echo-server-deploy-lls6f"}
{"level":"debug","ts":"2021-01-14T14:19:52.422Z","logger":"controller-runtime.controller","msg":"Successfully Reconciled","controller":"deployitem","request":"landscaper-local-test/example-echo-server-deploy-lls6f"}
{"level":"debug","ts":"2021-01-14T14:19:52.423Z","logger":"controller-runtime.controller","msg":"Successfully Reconciled","controller":"installation","request":"landscaper-local-test/example-echo-server"}
{"level":"info","ts":"2021-01-14T14:19:52.423Z","logger":"controllers.Installations","msg":"reconcile","resource":"landscaper-local-test/example-echo-server"}
{"level":"error","ts":"2021-01-14T14:19:52.428Z","logger":"controller-runtime.controller","msg":"Reconciler error","controller":"execution","request":"landscaper-local-test/example-echo-server","error":"Operation cannot be fulfilled on executions.landscaper.gardener.cloud \"example-echo-server\": the object has been modified; please apply your changes to the latest version and try again"}
{"level":"debug","ts":"2021-01-14T14:19:52.433Z","logger":"controller-runtime.controller","msg":"Successfully Reconciled","controller":"installation","request":"landscaper-local-test/example-echo-server"}
{"level":"error","ts":"2021-01-14T14:19:53.023Z","logger":"controllers.HelmDeployer","msg":"unable to update status","error":"Operation cannot be fulfilled on deployitems.landscaper.gardener.cloud \"example-echo-server-deploy-lls6f\": the object has been modified; please apply your changes to the latest version and try again"}
{"level":"error","ts":"2021-01-14T14:19:53.023Z","logger":"controller-runtime.controller","msg":"Reconciler error","controller":"deployitem","request":"landscaper-local-test/example-echo-server-deploy-lls6f","error":"Object 'Kind' is missing in 'unstructured object has no kind'"}
```

</details>

```
k get installations

NAME                  PHASE         CONFIGGEN   EXECUTION             AGE
example-echo-server   Progressing               example-echo-server   12m

k get executions
NAME                  PHASE         EXPORTREF                          AGE
example-echo-server   Progressing                                      12m

k get deployitem
NAME                               TYPE                             PHASE       EXPORTREF   AGE
example-echo-server-deploy-lls6f   landscaper.gardener.cloud/helm   Failed                  13m
```

The deployitem:
```
k get deployitem example-echo-server-deploy-lls6f -oyaml

apiVersion: landscaper.gardener.cloud/v1alpha1
kind: DeployItem
metadata:
  annotations:
    execution.landscaper.gardener.cloud/dependsOn: ""
  creationTimestamp: "2021-01-14T14:19:52Z"
  finalizers:
  - finalizer.landscaper.gardener.cloud
  generateName: example-echo-server-deploy-
  generation: 1
  labels:
    execution.landscaper.gardener.cloud/managed-by: example-echo-server
    execution.landscaper.gardener.cloud/name: deploy
  managedFields:
  - apiVersion: landscaper.gardener.cloud/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:execution.landscaper.gardener.cloud/dependsOn: {}
        f:finalizers:
          .: {}
          v:"finalizer.landscaper.gardener.cloud": {}
        f:generateName: {}
        f:labels:
          .: {}
          f:execution.landscaper.gardener.cloud/managed-by: {}
          f:execution.landscaper.gardener.cloud/name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"814bcdd2-834f-467c-a6ed-d2411cc06564"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        .: {}
        f:config:
          .: {}
          f:apiVersion: {}
          f:chart:
            .: {}
            f:ref: {}
          f:kind: {}
          f:name: {}
          f:namespace: {}
          f:updateStrategy: {}
        f:target:
          .: {}
          f:name: {}
          f:namespace: {}
        f:type: {}
      f:status:
        .: {}
        f:lastError:
          .: {}
          f:lastTransitionTime: {}
          f:lastUpdateTime: {}
          f:message: {}
          f:operation: {}
          f:reason: {}
        f:observedGeneration: {}
        f:phase: {}
    manager: landscaper-controller
    operation: Update
    time: "2021-01-14T14:24:54Z"
  name: example-echo-server-deploy-lls6f
  namespace: landscaper-local-test
  ownerReferences:
  - apiVersion: landscaper.gardener.cloud/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Execution
    name: example-echo-server
    uid: 814bcdd2-834f-467c-a6ed-d2411cc06564
  resourceVersion: "28640"
  uid: 4b13e15b-fe4a-4f49-abbb-51648ff16e20
spec:
  config:
    apiVersion: helm.deployer.landscaper.gardener.cloud/v1alpha1
    chart:
      ref: oci-registry.landscaper-local-test.svc.cluster.local:5000/echo-server:v1.1.0
    kind: ProviderConfiguration
    name: echo-server
    namespace: landscaper-example
    updateStrategy: patch
  target:
    name: test-target
    namespace: landscaper-local-test
  type: landscaper.gardener.cloud/helm
status:
  lastError:
    lastTransitionTime: "2021-01-15T12:07:08Z"
    lastUpdateTime: "2021-01-15T12:07:10Z"
    message: Object 'Kind' is missing in 'unstructured object has no kind'
    operation: ApplyObjects
    reason: GetObject
  observedGeneration: 0
  phase: Failed

```

Noteworthy: the echo server is installed in the target cluster and works.

**What you expected to happen**:
installation status succeeded and no error logs.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install landscaper with following helm values:
```
landscaper:
  registryConfig: # contains optional oci secrets
    allowPlainHttpRegistries: true
    secrets: {}
#     <name>: <docker config json>

  deployers:
  - container
  - helm
#  - mock

```
2. push echo server chart from https://storage.googleapis.com/sap-hub-test/echo-server-1.1.0.tgz to the OCI
3. Apply the installation.yaml:
```
apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: example-echo-server
spec:

  blueprint:
    inline:
      filesystem:
        blueprint.yaml: |
          apiVersion: landscaper.gardener.cloud/v1alpha1
          kind: Blueprint
          
          imports:
          - name: cluster
            targetType: landscaper.gardener.cloud/kubernetes-cluster
          
          - name: appname
            schema:
              type: string
          
          - name: appnamespace
            schema:
              type: string
          
          deployExecutions:
          - name: default
            type: GoTemplate
            template: |
              deployItems:
              - name: deploy
                type: landscaper.gardener.cloud/helm
                target:
                  name: {{ .imports.cluster.metadata.name }}
                  namespace: {{ .imports.cluster.metadata.namespace }}
                config:
                  apiVersion: helm.deployer.landscaper.gardener.cloud/v1alpha1
                  kind: ProviderConfiguration
          
                  chart:
                    ref: "oci-registry.landscaper-local-test.svc.cluster.local:5000/echo-server:v1.1.0"
          
                  updateStrategy: patch
          
                  name: {{ .imports.appname }}
                  namespace: {{ .imports.appnamespace }}          

  imports:
    targets:
    - name: cluster
      target: "#test-target"
    
  importDataMappings:
    appname: echo-server
    appnamespace: landscaper-example

```

**Anything else we need to know?**:

**Environment**:

- Landscaper version: v0.4.0-dev-2c856ff658ee4836bd330bee3af434207feb2bee
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T08:38:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Others:
