### ISSUE TITLE
[RFC] Dependency Management

### ISSUE THREAD

**Issue by kramerul** [gardener/landscaper#97]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority normal

# Dependency Management

## Motivation

This proposal is motivate by [the wish to have a homebrew like user experince](https://github.com/gardener/landscaper/issues/60) and also
by the [missing dependency management in landscaper](https://github.com/gardener/landscaper/issues/65).

## Idea

By introducing some kind of gossip between *installation components*, it's possible to install software in a modular way also covering dynamic dependency resolution.

![Dependencies](https://user-images.githubusercontent.com/13213351/105476542-0f3bcf00-5ca1-11eb-9589-b514a2ac4232.png)

## Concept

1. All installation models are implemented as docker containers 
2. Each installation model has 2 entry points
   * `apply`, which tries to apply this component to a given target in an idempotent way
   * `delete`, which removes the component from the given target
3. Parameters to those entry points are passed as YAML.
4. The entry points return their results also as YAML.
3. The component can answer an `apply` request with an `DependencyMissing` error, which includes the missing components. It can reply to an `apply` request with `DependencyMissing` as often as it's required to get all dependencies.
4. All values returned from the installation of a dependency are passed to the requesting *installation component*.

![ComponentDependencies](https://user-images.githubusercontent.com/13213351/105476563-15ca4680-5ca1-11eb-861c-8201ad5f7698.png)

### Dependency Types

It could be useful to support more than *installation components* as dependency types.

It might also be nice to have dependencies on secrets  provided by a secret manager (e.g. vault) or services provided by a service manager 

```yaml
dependencies:
  database:
    type: service-manager
    service: postgres
    plan: huge
  ipd:
    type: secret
    name: IDP_CONFIGURATION
```

### Sharing components

A component can specify, that a dependency can be shared. In that case the dependency will only be installed once, if it's requested by different components. This will require some kind of merging of installation parameters. Therefore, the `apply` entry point will receive the parameters provided by all dependency requesters. If component `C` is required from `A` and `B`, it could look like this:

```yaml
parameters:
  # parameters required by component A
  - t-shirt-size: XL
    nodes: 6
  # parameters required by component B
  - t-shirt-size: L
    nodes: 4  
```

The shared component `C` needs to find a parameter set which fits to both requirements. In this case it could be

```yaml
t-shirt-size: XL
nodes: 6
```

It's essential that components that can be shared have a small set of parameters for which consensus can be easily reached.

### Versions

All versions should be specified by semver constraints. This will make it easier 
* to use already installed components
* to patch software installation without changing the *installation component* which requested a dependency
* to also use fixed versions

### Component Descriptors

To have everything bundled into one *package* it might be useful to introduce a third entrypoint: `component-descriptors`.
This entry point can be called to get a list of all required images. The returned result should contain a list of images with version constraints. 

```yaml
images:
  docker.io/ubuntu: >=16
  docker.io/cloud-controller-api: ~ 7.0
```

This endpoint will be called before apply. The list of images to be used can then be passed in the parameters for the `apply` entry point.

```yaml
images:
  docker.io/ubuntu: articatory-dmz/ubuntu@sha:1234234523424
  docker.io/cloud-controller-api: articatory-dmz/cloud-controller-api@sha:123jhqwf8qwe4
```

### Reconciliation

The `apply` entry point of each *installation component* will be called on a regular base.

### Wrapping helm chart

Helm charts are not able to return values. For this, it's required to wrap them into docker images. This could be done by a simple tool. As alternative, it might be useful to directly accept helm charts as *installation component*.

### helm

Compatibility layers should be possible in both directions: wrapping helm charts as *installation component* and also *installation components*  as helm chart. The second one can be achieved using helm pre install hooks.

### kapp

kapp and ytt can be also packaged into a docker image together with the required ytt files.

### ClusterBOM

The helm-wrapped *installation components* can also be used in a ClusterBOM.

## Migration

* `Blueprints` will become Docker Images
* `ComponentDescriptors` will be included into those Docker Images
* `Installations` will be used to call the entry points of the Docker Images
* Value interpolation will be done inside the *installation component* (docker image). Go templating or `spiff` will no longer be required.

## POC

A POC for this proposal implemented in plain go can be found [here](https://github.com/kramerul/landep)

### Declarative Description

This concept in parts violates the principle of a declarative description of a target state because there is some logic running inside the entry points. 

This logic should be kept as minimal as possible.

## Summary

With this quite simple approach it will be possible to manage software installations including dependencies.
